Vagrant.configure("2") do |config|
  config.vm.box="centos/7"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.network "private_network", type: "dhcp" 
  # config.vm.network "private_network", ip: "192.168.1.50"
end
