Vagrant.configure("2") do |config|
  config.vm.define "target0" do |target0|
    target0.vm.box = "centos/7"
    target0.vm.network "private_network", ip: "192.168.100.100"
    target0.vm.hostname = "target0"
    # target0.vm.synced_folder "~/playbooks", "/home/vagrant/playbooks"
  end

  config.vm.define "target1" do |target1|
    target1.vm.box = "centos/7"
    target1.vm.network "private_network", ip: "192.168.100.101"
    target1.vm.hostname = "target1"
  end

  config.vm.define "target2" do |target2|
    target2.vm.box = "centos/7"
    target2.vm.network "private_network", ip: "192.168.100.102"
    target2.vm.hostname = "target2"
  end
end
