Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.network "private_network", ip: "10.0.0.20"
    master.vm.hostname = "master"

    master.vm.provider "virtualbox" do |vb|
      vb.memory = 2048 
      vb.cpus = 2
    end

  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/bionic64"
    node1.vm.network "private_network", ip: "10.0.0.21"
    node1.vm.hostname = "node1"

    node1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/bionic64"
    node2.vm.network "private_network", ip: "10.0.0.22"
    node2.vm.hostname = "node2"

    node2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

  end
end
